name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-cluster:
    runs-on: self-hosted

    steps:

    # Destroy Terraform AKS Resources
    - name: Checkout this Github repository
      uses: actions/checkout@v4

    - name: Login to Microsoft Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Move /deploy contents to /terraform
      run: |
        mv deploy/* .
      working-directory: ./terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize and validate Terraform configuration
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init && terraform validate
      working-directory: ./terraform

    - name: Destory Terraform Resources
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        USER_OBJECT_ID: ${{ secrets.MY_USER_OBJECT_ID }}
      run: |
        set -e

        cat <<EOF > terraform.tfvars.json
        {
          "my_user_object_id": "$USER_OBJECT_ID",
          "github_runner_token": "$RUNNER_TOKEN"
        }
        EOF

        echo "Verifying kubectl access"
        kubectl get ns -A

        echo "Attempting to destroy AKS cluster (max 3 attempts)..."
        for destroy in {1..3}; do
          echo "Attempt $destroy..."
          terraform destroy -target=azurerm_kubernetes_cluster.time_api_cluster --auto-approve && break || {
            echo "Terraform destroy failed (attempt $destroy)."
            if [ "$destroy" -lt 3 ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
            else
              echo "All attempts failed..."
              exit 1
            fi
          }
        done
      working-directory: ./terraform
    
  destroy-runner-vm:
    needs: destroy-cluster
    runs-on: ubuntu-latest

    steps:

    # Destroy Remaining Terraform Resources
    - name: Checkout this Github repository
      uses: actions/checkout@v4

    - name: Move /deploy contents to /terraform
      run: |
        mv deploy/* .
      working-directory: ./terraform

    - name: Login to Microsoft Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize and validate Terraform configuration
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init && terraform validate
      working-directory: ./terraform

    - name: Destory Terraform Resources
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        USER_OBJECT_ID: ${{ secrets.MY_USER_OBJECT_ID }}
      run: |
        cat <<EOF > terraform.tfvars.json
        {
          "my_user_object_id": "$USER_OBJECT_ID",
          "github_runner_token": "$RUNNER_TOKEN"
        }
        EOF
        
        terraform destroy --auto-approve
      working-directory: ./terraform

